---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
- name: "PENTEST | download file"
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop: "{{ pentest_git | flatten(levels=1) }}"
  tags:
    - pentest
    - pre
