---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
- name: "PENTEST | download | get file from url"
  become: true
  become_user: "{{ outer_item }}"
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop: "{{ pentest_download | flatten(levels=1) }}"
  tags:
    - pentest
    - pre

# ------------------------------------------------------------------------------
- name: "PENTEST | download | create symlink"
  become: true
  become_user: "{{ outer_item }}"
  ansible.builtin.file:
    src: "{{ item.symlink.src }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item.symlink.name }}"
    state: link
  loop: "{{ pentest_download | flatten(levels=1) }}"
  when:
    - pentest_download is defined
    - item.symlink is defined
  tags:
    - pentest
    - gem
