---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
- name: "PENTEST | git root checkout"
  become: true
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
    force: "{{ item.force | default('true') | bool }}"
  loop: "{{ pentest_git_root | flatten(levels=1) }}"
  when: pentest_git_root is defined
  tags:
    - pentest
    - git-root

# --------------------------------------------------------------------------
- name: "PENTEST | git root checkout | set rights folder"
  become: true
  ansible.builtin.file:
    path: "{{ item.dest }}/"
    state: directory
    mode: "{{ item.mode_folder }}"
    owner: "{{ item.mode | default('root') }}"
    group: "{{ item.mode | default('root') }}"
  loop: "{{ pentest_git_root | flatten(levels=1) }}"
  when:
    - item.mode_folder is defined
  tags:
    - pentest
    - git-root

- name: "PENTEST | git root checkout | set rights inside folder"
  become: true
  ansible.builtin.file:
    path: "{{ item.dest }}/"
    state: directory
    recurse: true
    mode: "{{ item.mode_files }}"
    owner: "{{ item.mode | default('root') }}"
    group: "{{ item.mode | default('root') }}"
  loop: "{{ pentest_git_root | flatten(levels=1) }}"
  when:
    - item.mode_files is defined
  tags:
    - pentest
    - git-root
