---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
# CHECK IF SERVICE INSTALLED
- name: "PENTEST | snap | check if service installed"
  become: true
  ansible.builtin.command: which snap
  register: is_snap_exist
  changed_when: is_snap_exist.rc not in [0, 1]
  failed_when: is_snap_exist.rc not in [0, 1]
  when: pentest_snap is defined
  tags:
    - pentest
    - snap

# ------------------------------------------------------------------------------
- name: "PENTEST | snap | start udev and snapd"
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - udev
    - snapd
  when:
    - is_snap_exist.rc is defined
    - is_snap_exist.rc == 0
    - pentest_snap is defined
  tags:
    - molecule-idempotence-notest
    - pentest
    - snap

# ------------------------------------------------------------------------------
- name: "PENTEST | snap | install snap services"
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | bool }}"
  loop: "{{ pentest_snap | flatten(levels=1) }}"
  when:
    - is_snap_exist.rc is defined
    - is_snap_exist.rc == 0
    - pentest_snap is defined
  tags:
    - pentest
    - snap

# ------------------------------------------------------------------------------
- name: "PENTEST | snap | create snap alias"
  become: true
  community.general.snap_alias:
    name: "{{ item.name }}"
    alias: "{{ item.alias }}"
  loop: "{{ pentest_snap_alias | flatten(levels=1) }}"
  when:
    - is_snap_exist.rc is defined
    - is_snap_exist.rc == 0
    - pentest_snap_alias is defined
  tags:
    - molecule-idempotence-notest
    - pentest
    - snap
