---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
- name: "PENTEST | gem | install bundler"
  become: true
  community.general.gem:
    name: bundler
    state: latest
    user_install: false
  when: pentest_gem is defined
  tags:
    - pentest
    - gem

# ------------------------------------------------------------------------------
- name: "PENTEST | gem | git checkout"
  become: true
  ansible.builtin.git:
    repo: "{{ item.repository }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
  loop: "{{ pentest_gem | flatten(levels=1) }}"
  when: pentest_gem is defined
  tags:
    - pentest
    - gem

- name: "PENTEST | gem | install"
  become: true
  community.general.bundler:
    chdir: "{{ item.dest }}"
    state: "{{ item.state | default('present') }}"
    user_install: "{{ item.user_install | default(false) | bool }}"
  loop: "{{ pentest_gem | flatten(levels=1) }}"
  when: pentest_gem is defined
  tags:
    - pentest
    - gem
