---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "PENTEST | python | check python version for arg '--break-system-packages'"
  become: true
  ansible.builtin.set_fact:
    install_server_fact_py_extra_args: "--break-system-packages"
  when:
    - pentest_python_pip is defined
    - ansible_facts['python_version'] >= "3.11"
  tags:
    - pentest
    - python

# ------------------------------------------------------------------------------
- name: "PENTEST | python | install python packages by pip"
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "{{ install_server_fact_py_extra_args | default('') }}"
  loop: "{{ pentest_python_pip | flatten(levels=1) }}"
  when: pentest_python_pip is defined
  tags:
    - molecule-idempotence-notest
    - pentest
    - python
