---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
- name: "PENTEST | gem | install services"
  become: true
  become_user: "{{ outer_item }}"
  community.general.gem:
    name: "{{ item }}"
    state: latest
    user_install: false
    install_dir: "{{ ansible_env.HOME }}/gems"
  loop: "{{ pentest_gem | flatten(levels=1) }}"
  when: pentest_gem is defined
  tags:
    - pentest
    - gem

# ------------------------------------------------------------------------------
- name: "PENTEST | gem | git checkout"
  become: true
  become_user: "{{ outer_item }}"
  ansible.builtin.git:
    repo: "{{ item.repository }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
  loop: "{{ pentest_gem_repo | flatten(levels=1) }}"
  when: pentest_gem_repo is defined
  tags:
    - pentest
    - gem

- name: "PENTEST | gem | bundler install"
  become: true
  become_user: "{{ outer_item }}"
  community.general.bundler:
    chdir: "{{ item.dest }}"
    state: latest
    user_install: true
    executable: "{{ ansible_env.HOME }}/gems/bin/bundle"
    gem_path: "{{ ansible_env.HOME }}/gems/"
    gemfile: "{{ ansible_env.HOME }}/gems/"
  loop: "{{ pentest_gem_repo | flatten(levels=1) }}"
  when: pentest_gem_repo is defined
  tags:
    - pentest
    - gem

# ------------------------------------------------------------------------------
- name: "PENTEST | gem | create symlink"
  become: true
  become_user: "{{ outer_item }}"
  ansible.builtin.file:
    src: "{{ item.symlink.src }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item.symlink.name }}"
    state: link
  loop: "{{ pentest_gem_repo | flatten(levels=1) }}"
  when:
    - pentest_gem_repo is defined
    - item.symlink is defined
  tags:
    - pentest
    - gem
