---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
- name: "PENTEST | gem | install bundler"
  become: true
  community.general.gem:
    name: bundler
    state: present
    user_install: false
  when: pentest_gem is defined
  tags:
    - pentest
    - gem

# ------------------------------------------------------------------------------
- name: "PENTEST | gem | git checkout"
  become: true
  become_user: "{{ outer_item }}"
  ansible.builtin.git:
    repo: "{{ item.repository }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
  loop: "{{ pentest_gem | flatten(levels=1) }}"
  when: pentest_gem is defined
  tags:
    - pentest
    - gem

- name: "PENTEST | gem | install"
  become: true
  community.general.bundler:
    chdir: "{{ item.dest }}"
    state: present
    user_install: false
  loop: "{{ pentest_gem | flatten(levels=1) }}"
  when: pentest_gem is defined
  tags:
    - pentest
    - gem

# ------------------------------------------------------------------------------
- name: "PENTEST | gem | create symlink"
  become: true
  become_user: "{{ outer_item }}"
  ansible.builtin.file:
    src: "{{ item.symlink.src }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item.symlink.name }}"
    state: link
  loop: "{{ pentest_gem | flatten(levels=1) }}"
  when:
    - pentest_gem is defined
    - item.symlink is defined
  tags:
    - pentest
    - gem
