---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
- name: "PENTEST | vscode"
  become: true
  become_user: "{{ outer_item }}"
  when: pentest_vscode_ext is defined
  tags:
    - pentest
    - per-user
    - vscode
  block:
    - name: "PENTEST | vscode | check if vs code is installed"
      ansible.builtin.shell: set -o pipefail && command -v code >/dev/null 2>&1
      args:
        executable: /bin/bash
      register: is_code_installed
      changed_when: false
      check_mode: false

    - name: "PENTEST | vscode | install extensions"
      ansible.builtin.command: "code --install-extension {{ item }}"
      loop: "{{ pentest_vscode_ext | flatten(levels=1) }}"
      changed_when: false
      failed_when: false
      when: is_code_installed.rc == 0

# ------------------------------------------------------------------------------
- name: "PENTEST | firefox-plugins | global"
  become: true
  become_user: "{{ outer_item }}"
  when: pentest_firefox_ext is defined
  tags:
    - pentest
    - per-user
    - firefox-plugins
  block:
    # --------------------------------------------------------------------------
    - name: "PENTEST | firefox-plugins | check if vs firefox is installed"
      ansible.builtin.shell: set -o pipefail && command -v firefox >/dev/null 2>&1
      args:
        executable: /bin/bash
      register: is_firefox_installed
      changed_when: false
      check_mode: false

    # --------------------------------------------------------------------------
    - name: "PENTEST | firefox-plugins | check if default Firefox profile exists"
      ansible.builtin.shell: |
        firefox_profiles=($(ls -d {{ ansible_env.HOME }}/{{ pentest_firefox_path }}/*.default 2>/dev/null))
        if [[ "${firefox_profiles[0]}" == "" ]]; then
          echo "profile_not_found"
        else
          echo "${firefox_profiles[0]}"
        fi
      args:
        executable: /bin/bash
      register: firefox_profile_output
      changed_when: false
      failed_when: firefox_profile_output.rc == 1

    - name: "PENTEST | firefox-plugins | save profile name"
      ansible.builtin.set_fact:
        pentest_firefox_profile_name: "{{ firefox_profile_output.stdout | basename }}"
      when: firefox_profile_output.stdout != "profile_not_found"

    # --------------------------------------------------------------------------
    - name: "PENTEST | firefox-plugins | create new Firefox profile"
      ansible.builtin.command: firefox --headless --createprofile ansible_profile
      changed_when: false
      failed_when: false
      when: firefox_profile_output.stdout == "profile_not_found"

    - name: "PENTEST | firefox-plugins | check if ansible_profile Firefox profile exists"
      ansible.builtin.shell: |
        firefox_profiles=($(ls -d {{ ansible_env.HOME }}/{{ pentest_firefox_path }}/*.ansible_profile 2>/dev/null))
        if [[ "${firefox_profiles[0]}" == "" ]]; then
          echo "profile_not_found"
        else
          echo "${firefox_profiles[0]}"
        fi
      args:
        executable: /bin/bash
      register: firefox_profile_ansible_profile_output
      changed_when: false
      failed_when: firefox_profile_ansible_profile_output.rc == 1
      when: firefox_profile_output.stdout == "profile_not_found"

    - name: "PENTEST | firefox-plugins | save profile name"
      ansible.builtin.set_fact:
        pentest_firefox_profile_name: "{{ firefox_profile_ansible_profile_output.stdout | basename }}"
      when: firefox_profile_ansible_profile_output.stdout != "profile_not_found"

    # --------------------------------------------------------------------------
    - name: "PENTEST | firefox-plugins | ensure directory exists | profile {{ pentest_firefox_profile_name }}"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/{{ pentest_firefox_path }}/{{ pentest_firefox_profile_name }}/extensions/"
        state: directory
        mode: "0755"
      when:
        - is_firefox_installed.rc is defined
        - is_firefox_installed.rc == 0

    # --------------------------------------------------------------------------
    - name: "PENTEST | firefox-plugins | download and install extensions | profile {{ pentest_firefox_profile_name }}"
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ ansible_env.HOME }}/{{ pentest_firefox_path }}/{{ pentest_firefox_profile_name }}/extensions/{{ item.id }}.xpi"
        mode: "0644"
      loop: "{{ pentest_firefox_ext | flatten(levels=1) }}"
      when:
        - is_firefox_installed.rc is defined
        - is_firefox_installed.rc == 0

# ------------------------------------------------------------------------------
- name: "PENTEST | firefox setup | copy user.js | profile {{ pentest_firefox_profile_name }}"
  become: true
  become_user: "{{ outer_item }}"
  ansible.builtin.template:
    src: "user.js.j2"
    dest: "{{ ansible_env.HOME }}/{{ pentest_firefox_path }}/{{ pentest_firefox_profile_name }}/user.js"
    mode: "0640"
  tags:
    - pentest
    - per-user
    - firefox-user
