---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
- name: "PENTEST | pre | create directory"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0777"
  loop:
    - "{{ pentest_path_base }}"
    - "{{ pentest_path_tools }}"
    - "{{ pentest_path_docker }}"
  tags:
    - pentest
    - pre

# ------------------------------------------------------------------------------
- name: "PENTEST | pre | create symlink python3=>python"
  become: true
  ansible.builtin.file:
    src: "/usr/bin/python3"
    dest: "/usr/bin/python"
    state: link
  tags:
    - pentest
    - pre

# ------------------------------------------------------------------------------
- name: "PENTEST | pre | environment variables | profile zsh"
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/zsh/profile.d/tools.sh
    line: 'export {{ item.name }}="{{ item.value }}"'
    insertafter: EOF
    create: true
    mode: "0644"
  loop:
    - name: PATH
      value: "$PATH:/usr/local/go/bin"
    - name: GOPATH
      value: "$HOME/go"
    - name: PATH
      value: "$GOPATH/bin:$PATH"
    - name: GEM_HOME
      value: "$HOME/gems"
    - name: PATH
      value: "$HOME/gems/bin:$PATH"
    - name: PATH
      value: "$PATH:$HOME/.npm-packages/bin"
    - name: MANPATH
      value: "${MANPATH-$(manpath)}:$HOME/.npm-packages/share/man"
  tags:
    - pentest
    - pre

- name: "PENTEST | pre | environment variables | profile"
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/profile.d/tools.sh
    line: 'export {{ item.name }}="{{ item.value }}"'
    insertafter: EOF
    create: true
    mode: "0644"
  loop:
    - name: PATH
      value: "$PATH:/usr/local/go/bin"
    - name: GOPATH
      value: "$HOME/go"
    - name: PATH
      value: "$GOPATH/bin:$PATH"
    - name: GEM_HOME
      value: "$HOME/gems"
    - name: PATH
      value: "$HOME/gems/bin:$PATH"
    - name: PATH
      value: "$PATH:$HOME/.npm-packages/bin"
    - name: MANPATH
      value: "${MANPATH-$(manpath)}:$HOME/.npm-packages/share/man"
  tags:
    - pentest
    - pre
