---
# tasks file for ansible-pentest

# ------------------------------------------------------------------------------
- name: "PENTEST | pre | create directory"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0777"
  loop:
    - "{{ pentest_path_base }}"
    - "{{ pentest_path_tools }}"
    - "{{ pentest_path_docker }}"
  tags:
    - pentest
    - pre
